version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 636920964135.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - docker build -t gatewaypos -f ./api/Dockerfile .
      - docker tag gatewaypos:latest 636920964135.dkr.ecr.us-east-2.amazonaws.com/gatewaypos:latest

      - docker pull postgres:14
      - docker tag postgres:latest 636920964135.dkr.ecr.us-east-2.amazonaws.com/postgres:latest

      - docker pull redis
      - docker tag redis:latest 636920964135.dkr.ecr.us-east-2.amazonaws.com/redis:latest
  post_build:
    commands:
      - docker push 636920964135.dkr.ecr.us-east-2.amazonaws.com/gatewaypos:latest
      - docker push 636920964135.dkr.ecr.us-east-2.amazonaws.com/postgres:latest
      - docker push 636920964135.dkr.ecr.us-east-2.amazonaws.com/redis:latest