apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: culqi-postgres
  name: culqi-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: culqi-postgres
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/gateway-pos-default: "true"
        io.kompose.service: culqi-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: culqi_pg
            - name: POSTGRES_USER
              value: postgres
          image: 636920964135.dkr.ecr.us-east-2.amazonaws.com/postgres:latest
          name: culqi-postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
