apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: culqi-gateway-pos
  name: culqi-gateway-pos
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: culqi-gateway-pos
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/gateway-pos-default: "true"
        io.kompose.service: culqi-gateway-pos
    spec:
      containers:
        - env:
            - name: PORT
              value: "3000"
            - name: POSTGRES_HOST
              value: culqi_postgres
            - name: POSTGRES_PASSWORD
              value: culqi_pg
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: REDIS_URL
              value: redis://culqi-redis:6379
          image: localhost/gateway_pos
          name: culqi-gateway-pos
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /app/src
              name: culqi-gateway-pos-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: culqi-gateway-pos-claim0
          persistentVolumeClaim:
            claimName: culqi-gateway-pos-claim0
            readOnly: true
status: {}
